# This travis workflow is part of the original template
sudo:          false
language:      node_js
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules
